### ISSUE TITLE
Mapa mental web 3.0

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/mapa-mental-web-3-Nayee123#1]
[Nayeli Anai González López .pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Nayee123/files/8385549/Nayeli.Anai.Gonzalez.Lopez.pdf)

**Comment by Yabin-2021** [comment]
Buen trabajo

20 %

**Comment by josealfredo79** [comment]
El mapa mental debe esta mas completo....para la próxima lo regreso...
